#export PYTHONPATH=$PYTHONPATH:$GITDIR/PyKalman
export PYTHONPATH=$PYTHONPATH:$GITDIR/PyKalman/Base/
export PYTHONPATH=$PYTHONPATH:$GITDIR/PyKalman/KBase/
export PYTHONPATH=$PYTHONPATH:$GITDIR/PyKalman/Irene/
export PYTHONPATH=$PYTHONPATH:$GITDIR/PyKalman/KLog/
export PYTHONPATH=$PYTHONPATH:$GITDIR/PyKalman/KalmanFilter/